<?php
/**
 * Crypt is only a utility class to encrypt strings before store to
 * the database.
 *
 * It uses random string generated by WordPress Salt.
 *
 */

namespace Dm\Libs;

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly.

class Crypt {

    public static function encryptString($string) {
        $key = hash('sha256', AUTH_KEY);
        $iv = substr(hash('sha256', NONCE_KEY), 0, 16);

        $encrypted = openssl_encrypt($string, "AES-256-CBC", $key, 0, $iv);
        return base64_encode($encrypted);
    }

    public static function decryptString($string) {
        $key = hash('sha256', AUTH_KEY);
        $iv = substr(hash('sha256', NONCE_KEY), 0, 16);

        return openssl_decrypt(base64_decode($string), "AES-256-CBC", $key, 0, $iv);
    }

}
